require.config({
	baseUrl:"/",
	paths:{
		"jquery":"lib/jquery/jquery-1.12.4.min",
		"cookie":"lib/jquery_plugins/jquery.cookie",
		"zoom":"lib/jquery_plugins/jquery.elevateZoom-2.2.3.min",
		"fly":"lib/jquery_plugins/jquery.fly.min",
		"template":"lib/arttemplate/template-native",
		"load":"js/loadFooterHeader"
	}
});
